export const FakeTutors = [
  {
    firstName: "Miki",
    lastName: "Okudera",
    description: "Ex Facebook, Ex Google, Ex Husband, Tech-lead ",
    courses: "Teaches Python, Java",
    languages: "Speaks English (Native), Russian (Native), Japanese (C2)",
    education: "Computer Science, University Of Tokyo",
    aboutMe: "",
    tutorId: 42,
  },
  {
    firstName: "Miki",
    lastName: "Okudera",
    description: "Ex Facebook, Ex Google, Ex Husband, Tech-lead ",
    courses: "Teaches Python, Java",
    languages: "Speaks English (Native), Russian (Native), Japanese (C2)",
    education: "Computer Science, University Of Tokyo",
    aboutMe: "",
    tutorId: 42,
  },
  {
    firstName: "Miki",
    lastName: "Okudera",
    description: "Ex Facebook, Ex Google, Ex Husband, Tech-lead ",
    courses: "Teaches Python, Java",
    languages: "Speaks English (Native), Russian (Native), Japanese (C2)",
    education: "Computer Science, University Of Tokyo",
    aboutMe: "",
    tutorId: 42,
  },
  {
    firstName: "Miki",
    lastName: "Okudera",
    description: "Ex Facebook, Ex Google, Ex Husband, Tech-lead ",
    courses: "Teaches Python, Java",
    languages: "Speaks English (Native), Russian (Native), Japanese (C2)",
    education: "Computer Science, University Of Tokyo",
    aboutMe: "",
    tutorId: 42,
  },
  {
    firstName: "Miki",
    lastName: "Okudera",
    description: "Ex Facebook, Ex Google, Ex Husband, Tech-lead ",
    courses: "Teaches Python, Java",
    languages: "Speaks English (Native), Russian (Native), Japanese (C2)",
    education: "Computer Science, University Of Tokyo",
    aboutMe: "",
    tutorId: 42,
  },
  {
    firstName: "Miki",
    lastName: "Okudera",
    description: "Ex Facebook, Ex Google, Ex Husband, Tech-lead ",
    courses: "Teaches Python, Java",
    languages: "Speaks English (Native), Russian (Native), Japanese (C2)",
    education: "Computer Science, University Of Tokyo",
    aboutMe: "",
    tutorId: 42,
  },
  {
    firstName: "Miki",
    lastName: "Okudera",
    description: "Ex Facebook, Ex Google, Ex Husband, Tech-lead ",
    courses: "Teaches Python, Java",
    languages: "Speaks English (Native), Russian (Native), Japanese (C2)",
    education: "Computer Science, University Of Tokyo",
    aboutMe: "",
    tutorId: 42,
  },
];
